name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: set up
      if: matrix.os == 'ubuntu-latest'
      run: ./linux_config.sh 

    - name: build check
      if: matrix.os == 'ubuntu-latest'
      run: make
